# Generated by Django 4.2.3 on 2023-09-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_skill_score_alter_certificate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_icon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
