# Generated by Django 4.2.3 on 2023-09-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skill_is_icon_alter_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
