# Generated by Django 4.2.3 on 2023-09-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='skills'),
        ),
    ]
