# Generated by Django 4.2.3 on 2023-09-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_skill_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='desription',
            new_name='description',
        ),
    ]
